import fs from 'node:fs'
import path from 'node:path'

import { readGilNodeGraph } from '../injector/reader.js'
import type { NodeDetail, NodeGraphDetail, VariableDetail } from '../injector/reader.js'
import { createUi } from './ui.js'

const ui = createUi()

export type ScaffoldOptions = {
  id: string
  out?: string
  force?: boolean
}

// Map from IR typeName to the TS constructor name used in scaffold output
const TYPE_TO_CONSTRUCTOR: Record<string, string> = {
  bool: 'bool',
  int: 'int',
  float: 'float',
  str: 'str',
  vec3: 'vec3',
  guid: 'guid',
  entity: 'entity',
  prefab_id: 'prefabId',
  config_id: 'configId',
  faction: 'faction',
  entity_list: 'list',
  int_list: 'list',
  float_list: 'list',
  str_list: 'list',
  bool_list: 'list',
  vec3_list: 'list',
  guid_list: 'list',
  dict: 'dict'
}

// Collect which constructors are needed for the variable declarations
function collectImports(variables: VariableDetail[]): string[] {
  const needed = new Set<string>()
  for (const v of variables) {
    const ctor = TYPE_TO_CONSTRUCTOR[v.typeName]
    if (ctor && ctor !== 'list' && ctor !== 'dict') {
      needed.add(ctor)
    }
  }
  // Always include g
  const constructors = ['g', ...Array.from(needed).sort()]
  return constructors
}

function buildDefaultValue(v: VariableDetail): string {
  if (v.initialValue !== undefined) {
    const ctor = TYPE_TO_CONSTRUCTOR[v.typeName]
    if (!ctor || ctor === 'list' || ctor === 'dict') return v.initialValue
    return `${ctor}(${v.initialValue})`
  }
  // Fallback defaults by type
  switch (v.typeName) {
    case 'bool': return 'bool(false)'
    case 'int': return 'int(0)'
    case 'float': return 'float(0)'
    case 'str': return 'str("")'
    case 'vec3': return 'vec3(0, 0, 0)'
    case 'guid': return 'guid(0)'
    case 'entity': return 'entity(0)'
    case 'prefab_id': return 'prefabId(0)'
    case 'config_id': return 'configId(0)'
    case 'faction': return 'faction(0)'
    default: return `/* ${v.typeName} */`
  }
}

function nodeIdNameToCamel(key: string): string {
  return key
    .replace(/__.*$/, '')
    .toLowerCase()
    .replace(/_([a-z])/g, (_, c: string) => (c as string).toUpperCase())
}

// Group non-event nodes by their event entry (the event entry node's outflow chain)
function groupNodesByEntry(
  nodes: NodeDetail[]
): Map<number, NodeDetail[]> {
  const entryNodes = nodes.filter((n) => n.isEventEntry)
  const result = new Map<number, NodeDetail[]>()
  const allNodesByIndex = new Map<number, NodeDetail>(nodes.map((n) => [n.index, n]))

  for (const entry of entryNodes) {
    const collected: NodeDetail[] = []
    const visited = new Set<number>([entry.index])
    const queue = [...entry.outflowTargets]
    while (queue.length > 0) {
      const idx = queue.shift()!
      if (visited.has(idx)) continue
      visited.add(idx)
      const node = allNodesByIndex.get(idx)
      if (!node) continue
      if (!node.isEventEntry) {
        collected.push(node)
        queue.push(...node.outflowTargets)
      }
    }
    result.set(entry.index, collected)
  }
  return result
}

function generateScaffold(detail: NodeGraphDetail, gilFileName: string): string {
  const lines: string[] = []

  lines.push(`// Auto-generated scaffold from: ${gilFileName} (id=${detail.id})`)
  lines.push(`// Graph: ${detail.name || '(unnamed)'} (type: ${detail.graphTypeName})`)
  lines.push(`// Generated by: gsts scaffold`)
  lines.push(`// TODO: Fill in event handler logic below.`)
  lines.push(``)

  // Build import line
  const constructors = collectImports(detail.variables)
  lines.push(`import { ${constructors.join(', ')} } from 'genshin-ts'`)
  lines.push(``)

  // Determine graph type option
  const typeOpt = detail.graphTypeName !== 'entity' && detail.graphTypeName !== 'unknown'
    ? `, type: '${detail.graphTypeName}' as const`
    : ''

  // Start server definition
  const hasVariables = detail.variables.length > 0
  const entryNodes = detail.nodes.filter((n) => n.isEventEntry)
  const nodesByEntry = groupNodesByEntry(detail.nodes)

  if (hasVariables) {
    lines.push(`export default g.server({`)
    lines.push(`  id: ${detail.id}${typeOpt},`)
    lines.push(`  variables: {`)
    for (const v of detail.variables) {
      lines.push(`    ${v.name}: ${buildDefaultValue(v)},`)
    }
    lines.push(`  }`)
    lines.push(`})`)
  } else {
    lines.push(`export default g.server({ id: ${detail.id}${typeOpt} })`)
  }

  // Event handler stubs
  if (entryNodes.length === 0) {
    lines.push(`  // No event handler nodes found in this graph.`)
    lines.push(`  // Use .on('eventName', (evt, f) => { ... }) to add handlers.`)
  } else {
    for (const entry of entryNodes) {
      if (entry.signalName) {
        // Signal handler: use .onSignal('signalName', ...)
        lines.push(`  .onSignal('${entry.signalName}', (_evt, _f) => {`)
      } else {
        // Regular event handler: entry.typeName is already camelCase from reader.ts
        lines.push(`  .on('${entry.typeName}', (_evt, _f) => {`)
      }

      const bodyNodes = nodesByEntry.get(entry.index) ?? []
      if (bodyNodes.length > 0) {
        lines.push(`    // Original nodes in this handler:`)
        for (const n of bodyNodes) {
          const sig = n.signalName ? ` (signal: "${n.signalName}")` : ''
          lines.push(`    //   #${n.index} ${n.typeName}${sig}`)
        }
        lines.push(`    // TODO: implement handler`)
      } else {
        lines.push(`    // TODO: implement handler`)
      }
      lines.push(`  })`)
    }
  }

  lines.push(``)
  return lines.join('\n')
}

export async function runScaffold(
  filePath: string,
  cmdOpts: ScaffoldOptions
): Promise<void> {
  const targetId = parseInt(cmdOpts.id, 10)
  if (!Number.isFinite(targetId)) {
    ui.error(`Invalid --id: ${cmdOpts.id}`)
    process.exitCode = 1
    return
  }

  let gilBytes: Uint8Array
  try {
    gilBytes = new Uint8Array(fs.readFileSync(filePath))
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    ui.error(`Cannot read file: ${msg}`)
    process.exitCode = 1
    return
  }

  let detail: NodeGraphDetail
  try {
    detail = readGilNodeGraph(gilBytes, targetId)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    ui.error(msg.replace('[error]', '').trim())
    process.exitCode = 1
    return
  }

  // Determine output path
  const gilFileName = path.basename(filePath)
  const graphNamePart = (detail.name || `graph_${detail.id}`)
    .replace(/^_GSTS_?/, '')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .toLowerCase() || `graph_${detail.id}`
  const defaultOut = path.join(path.dirname(filePath), `${graphNamePart}.scaffold.ts`)
  const outPath = cmdOpts.out ?? defaultOut

  if (!cmdOpts.force && fs.existsSync(outPath)) {
    ui.error(`Output file already exists: ${outPath}. Use --force to overwrite.`)
    process.exitCode = 1
    return
  }

  const content = generateScaffold(detail, gilFileName)

  try {
    fs.mkdirSync(path.dirname(outPath), { recursive: true })
    fs.writeFileSync(outPath, content, 'utf8')
    ui.ok(`scaffold written -> ${outPath}`)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    ui.error(`Failed to write output: ${msg}`)
    process.exitCode = 1
  }
}
